### ISSUE TITLE
AttributeError: 'DataFrame' object has no attribute 'append'

### ISSUE THREAD

**Issue by 28YOGESH** [molecularsets/moses#107]
user: ~/moses$ python scripts/run.py
Traceback (most recent call last):
  File "scripts/run.py", line 7, in <module>
    from moses.models_storage import ModelsStorage
  File "/home/drkinshuk/moses/moses/__init__.py", line 2, in <module>
    from .metrics import get_all_metrics
  File "/home/drkinshuk/moses/moses/metrics/__init__.py", line 1, in <module>
    from .metrics import get_all_metrics, \
  File "/home/drkinshuk/moses/moses/metrics/metrics.py", line 11, in <module>
    from .utils import compute_fragments, average_agg_tanimoto, \
  File "/home/drkinshuk/moses/moses/metrics/utils.py", line 24, in <module>
    _mcf.append(_pains, sort=True)['smarts'].values]
  File "/home/drkinshuk/anaconda3/envs/my-rdkit-env/lib/python3.8/site-packages/pandas/core/generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'append'

#Please help me, how to solve this error and why it shows this error

**Comment by drigoni** [comment]
I guess you have installed pandas>=2.0. Try with a version of pandas<2.0
