### ISSUE TITLE
RuntimeError: 'lengths' argument should be a 1D CPU int64 tensor, but got 1D cuda:1 Long tensor

### ISSUE THREAD

**Issue by viko-3** [molecularsets/moses#97]
I run the code  use cuda, but I face this problem, so how can I solvie the problem?

> Traceback (most recent call last):
  File "scripts/run.py", line 219, in <module>
    main(config)
  File "scripts/run.py", line 199, in main
    train_model(config, model, train_path, test_path)
  File "scripts/run.py", line 127, in train_model
    trainer_script.main(model, trainer_config)
  File "/home/cyy/Code/moses/scripts/train.py", line 62, in main
    trainer.fit(model, train_data, val_data)
  File "/home/cyy/anaconda3/envs/moses/lib/python3.7/site-packages/moses/aae/trainer.py", line 284, in fit
    self._train(model, train_loader, val_loader, logger)
  File "/home/cyy/anaconda3/envs/moses/lib/python3.7/site-packages/moses/aae/trainer.py", line 219, in _train
    tqdm_data, criterions, optimizers)
  File "/home/cyy/anaconda3/envs/moses/lib/python3.7/site-packages/moses/aae/trainer.py", line 116, in _train_epoch
    latent_codes = model.encoder_forward(*encoder_inputs)
  File "/home/cyy/anaconda3/envs/moses/lib/python3.7/site-packages/moses/aae/model.py", line 109, in encoder_forward
    return self.encoder(*args, **kwargs)
  File "/home/cyy/anaconda3/envs/moses/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/cyy/anaconda3/envs/moses/lib/python3.7/site-packages/moses/aae/model.py", line 26, in forward
    x = pack_padded_sequence(x, lengths, batch_first=True)
  File "/home/cyy/anaconda3/envs/moses/lib/python3.7/site-packages/torch/nn/utils/rnn.py", line 249, in pack_padded_sequence
    _VF._pack_padded_sequence(input, lengths, batch_first)
RuntimeError: 'lengths' argument should be a 1D CPU int64 tensor, but got 1D cuda:1 Long tensor

**Comment by viko-3** [comment]
I fix it now.

**Comment by abdouskamel** [comment]
Hello @Cyy1216,
I have the same issue. Can you please tell me how you fixed it ?
Many thanks.

**Comment by viko-3** [comment]
> Hello @Cyy1216, I have the same issue. Can you please tell me how you fixed it ? Many thanks.

use length.cpu() to replace length

**Comment by abdouskamel** [comment]
It works, thanks.
